name: SurvivalMmo

main: Rubyliss\SurvivalMmo\Main

version: 0.0.1

api: [2.0.0,1.0.0,3.0.0-ALPHA1,3.0.0-ALPHA2,3.0.0-ALPHA3,3.0.0-ALPHA4,3.0.0-ALPHA5,3.0.0,3.0.0-ALPHA11,3.0.0-ALPHA10]

load: POSTWORLD

author: Rubyliss


description: An Mmo style plugin that bring levels to your minecraft pocket edition server

website: https://twitter.com/ZikenHDR

commands:
 #Name of the command. This is what people will type to execute the command.
 level:
  #Description to show in the Help command
  description: "See your level informations"
  #Usage message shown to the user if they type the command in incorrectly.
  usage: "/level"