name: SurvivalMmo

main: Rubyliss\SurvivalMmo\Main

version: 0.1.5

api: [2.0.0,1.0.0,3.0.0-ALPHA1,3.0.0-ALPHA2,3.0.0-ALPHA3,3.0.0-ALPHA4,3.0.0-ALPHA5,3.0.0,3.0.0-ALPHA11,3.0.0-ALPHA10]

load: POSTWORLD

author: Rubyliss


description: An Mmo style plugin that bring levels to your minecraft pocket edition server

website: https://twitter.com/ZikenHDR