---
#
#  █▄░▄█ ▀ █▄░█ █▀▀ █▀▀▄
#  █░█░█ █ █░▀█ █▀▀ █▐█▀
#  ▀░░░▀ ▀ ▀░░▀ ▀▀▀ ▀░▀▀
#
# - EXP Needed per miner level
MinerMaxExp: 10
# - Miner Level UP message
MinerLevelUpMessage: "§k§e!!§r §a§lMiner §r§7- You are now level :"
# - EXP per block broke
MinerExpPerBlock: 0.5
#
DisplayBlockBroken: true
#
#  █░░ █░█ █▄░▄█ █▀▄ █▀▀ █▀▀▄ ░░▀ ▄▀▄ ▄▀ █░▄▀
#  █░▄ █░█ █░█░█ █▀█ █▀▀ █▐█▀ ▄░█ █▀█ █░ █▀▄░
#  ▀▀▀ ░▀░ ▀░░░▀ ▀▀░ ▀▀▀ ▀░▀▀ ▀▀▀ ▀░▀ ░▀ ▀░▀▀
#
# - EXP Needed per lumberjack level
LumberjackMaxExp: 10
# - Miner Level UP message
LumberjackLevelUpMessage: "§k§e!!§r §a§lLumberjack §r§7- You are now level :"
# - EXP per block broke
LumberjackExpPerBlock: 0.5
#
#  █▀ ▄▀▄ █▀▀▄ █▄░▄█ █▀▀ █▀▀▄
#  █▀ █▀█ █▐█▀ █░█░█ █▀▀ █▐█▀
#  ▀░ ▀░▀ ▀░▀▀ ▀░░░▀ ▀▀▀ ▀░▀▀
#
# - EXP Needed per farmer level
FarmerMaxExp: 10
# - farmer Level UP message
FarmerLevelUpMessage: "§k§e!!§r §a§lLumberjack §r§7- You are now level :"
# - EXP per block broke
FarmerExpPerBlock: 0.5
# - EXP per block placed ( Seeds )
FarmerExpPerBlockPlace: 0.1
...